# Generated by Django 3.1.1 on 2020-09-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
        ('Kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitproduto',
            name='produtos_kit',
            field=models.ManyToManyField(related_name='produtos_kit', to='Produto.Produto'),
        ),
    ]
